### PR TITLE
Rename stakeholder need per Robb1994 issue #54

### LINKED ISSUE #54: Rename stakeholder need for Secondary Mission Objective 2.1
Mission Requirements document for Mission Requirement, 
_The SeaLion mission shall provide a means to validate an Impedance Probe (IP) in-orbit._,
is specified as a primary instead of a secondary requirement.

Should this be considered a primary or secondary mission objective?

### PR DESCRIPTION
**Pull request by kchiu002**
Close #54

### CODE REVIEW

**Comment by capsulecorplab** [comment]
@Robb1994 did we settle whether this should be a primary or secondary objective?

**Comment by Robb1994** [comment]
Dr. Asundi said he was going to send out a revision to the "MissionRequirements.doc". I think we should wait until we see that document before we start making additional changes.

**Review by Robb1994 — APPROVED** [review]

**Review by capsulecorplab — CHANGES_REQUESTED** [review]
This shouldn't affect any open PR's at the moment, so should be good to merge once version bump is addressed

**Review by capsulecorplab — APPROVED** [review]
LGTM

**Review by Robb1994 — COMMENTED** [review]
@capsulecorplab We now need to change id 2.1 statement with Multi-spectral Sensor (Ms-S) since VIR-S has been re-named.

**Comment by capsulecorplab** [comment]
> @capsulecorplab We now need to change id 2.1 statement with Multi-spectral Sensor (Ms-S) since VIR-S has been re-named.

Thanks! Opened an issue https://github.com/ODU-CGA-CubeSat/mission-conops/issues/139

**Pull request merged**
