### PR TITLE
Rename all files and references from .yml to .yaml

### LINKED ISSUE #91: reformat yaml file names, as per content style guide
Upon writing the style guide in #51, I noticed there's an inconsistent style used for yaml files in the `architecture/`. This issue will constitute a *breaking* change to the `version` in package.json

### PR DESCRIPTION
**Pull request by kchiu002**
Close #91

### CODE REVIEW

**Review by capsulecorplab — CHANGES_REQUESTED** [review]
Nice! We should also update the file names to be `PascalCase`, rather than `snake_case`. The yaml file names in the `derivedFrom` fields will allso need to be updated. Let's also bump the major version number in package.json to `2.0.0`.

**Review by capsulecorplab — CHANGES_REQUESTED** [review]
`templates/pdf-theme.yaml.liquid` should actually stay named `templates/pdf-theme.yml.liquid`, since the liquidoc tool has trouble parsing `.yaml` extension for some reason. Also, the derivedFrom field in Stakeholder Need 1.3 should be updated. Otherwise, should be good to go

**Comment by kchiu002** [comment]
> `templates/pdf-theme.yaml.liquid` should actually stay named `templates/pdf-theme.yml.liquid`, since the liquidoc tool has trouble parsing `.yaml` extension for some reason. Also, the derivedFrom field in Stakeholder Need 1.3 should be updated. Otherwise, should be good to go

Correction made to pdf-theme.yaml.liquid

Did you mean Stakeholder Need 1.4 instead? Or did you want me to add a derivedFrom to Stakeholder Need 1.3?

**Comment by capsulecorplab** [comment]
> > `templates/pdf-theme.yaml.liquid` should actually stay named `templates/pdf-theme.yml.liquid`, since the liquidoc tool has trouble parsing `.yaml` extension for some reason. Also, the derivedFrom field in Stakeholder Need 1.3 should be updated. Otherwise, should be good to go
> 
> Correction made to pdf-theme.yaml.liquid
> 
> Did you mean Stakeholder Need 1.4 instead? Or did you want me to add a derivedFrom to Stakeholder Need 1.3?

Correct; I meant 1.4 :slightly_smiling_face:

**Review by capsulecorplab — APPROVED** [review]
LGTM

**Pull request merged**
